function(ballistics_enable_coverage target_name)
    if(NOT BALLISTICS_ENABLE_COVERAGE)
        return()
    endif()
    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(${target_name} PRIVATE -O0 -g --coverage)
        target_link_options(${target_name} PRIVATE --coverage)
    else()
        message(WARNING "Coverage requested but unsupported by ${CMAKE_C_COMPILER_ID}")
    endif()
endfunction()
