function(ballistics_select_port out_source)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(${out_source} "${CMAKE_CURRENT_SOURCE_DIR}/src/port/linux_port.c" PARENT_SCOPE)
        message(STATUS "Ballistics port: Linux")
    else()
        set(${out_source} "${CMAKE_CURRENT_SOURCE_DIR}/src/port/unsupported_port.c" PARENT_SCOPE)
        message(WARNING "Ballistics port: unsupported platform fallback")
    endif()
endfunction()
